# This file was generated by GoReleaser. DO NOT EDIT.
cask "goban" do
  name "goban"
  desc "Self-hosted kanban board CLI with MCP server and Telegram bot support"
  homepage "https://github.com/icl00ud/goban"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goban"

  on_macos do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_amd64.tar.gz"
      sha256 "aa3786ce8751d84c117eccf51dd4e23b7092a3c4242ec3169ea187dfc9e11da6"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_arm64.tar.gz"
      sha256 "31bc464d021624aeb6db7cc757ec9925bd83e0292568f14bc331c9971faae0b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_amd64.tar.gz"
      sha256 "d74ea31a966e0068e5983cd0a7111d5a51b57dd99cdcb0945121a0a02d757a0c"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_arm64.tar.gz"
      sha256 "634bebbc79a09fa8093068cd5b5991cfae9545f5b772cdc07f62f03da846be99"
    end
  end

  # No zap stanza required
end
