# This file was generated by GoReleaser. DO NOT EDIT.
cask "goban" do
  name "goban"
  desc "Self-hosted kanban board CLI with MCP server and Telegram bot support"
  homepage "https://github.com/icl00ud/goban"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goban"

  on_macos do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_amd64.tar.gz"
      sha256 "fdb117edce7368d421bc5fad6a529475f54944d2107ba32689e799ae8dbb52c4"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_arm64.tar.gz"
      sha256 "bad27d7875494426f1839dca7c0dde631400c330beb66228ab5d2dba51817439"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_amd64.tar.gz"
      sha256 "f3bd35046b62c71d223b416c8a9eafee5ff231ec5e22a21ec9cbb0c9e62a2ee6"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_arm64.tar.gz"
      sha256 "3eea7037e76883891140a33cc4914010665bbd2b2f4a887b0f6ec0df03eb04f6"
    end
  end

  # No zap stanza required
end
