# This file was generated by GoReleaser. DO NOT EDIT.
cask "goban" do
  name "goban"
  desc "Self-hosted kanban board CLI with MCP server and Telegram bot support"
  homepage "https://github.com/icl00ud/goban"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goban"

  on_macos do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_amd64.tar.gz"
      sha256 "2c9364fb116cdf04b3b9ed7e0ccad75cdd9f5c56eff2e944e7d1d424993153e2"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_darwin_arm64.tar.gz"
      sha256 "4aeae7c430f1c0515395b91048049ebd7b3a249e9527fb5189848e59660634ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_amd64.tar.gz"
      sha256 "95afe0103d2f817e1ee8faa9afb375af338248e5fd19ddb19bcd003e7c060058"
    end
    on_arm do
      url "https://github.com/icl00ud/goban/releases/download/v#{version}/goban_#{version}_linux_arm64.tar.gz"
      sha256 "54bd836301659e03f6422587654327e36cf143a929165f83f93cb85785fdf471"
    end
  end

  # No zap stanza required
end
